config/routes.rb
Rails.application.routes.draw do

  get 'users/stats/:id',                to: 'users#stats'

  get 'projects/move_to_document/:id',  to: 'projects#move_to_document'
  get 'projects/move_to_access/:id',    to: 'projects#move_to_access'
  get 'projects/move_to_detail/:id',    to: 'projects#move_to_detail'
  get 'projects/all_download/:id',      to: 'projects#all_download'

  get 'documents/move_to_version/:id',  to: 'documents#move_to_version'

  post 'versions/download_pdf/',        to: 'versions#download_pdf'
  post 'versions/download_dxf/',        to: 'versions#download_dxf'
  get 'versions/make_current/:id',      to: 'versions#make_current'
  get 'checker/:encrypted_id',          to: 'versions#checker'
  
  get 'admin/projects',                 to: 'admin#projects'
  get 'admin/users',                    to: 'admin#users'
  get 'admin/new_user',                 to: 'admin#new_user'
  get 'admin/edit_user/:id',            to: 'admin#edit_user'
  get 'admin/logs',                     to: 'admin#logs'

  scope "(:locale)", locale: /en|fr|de/ do
    root 'static_pages#home'
    resource :session, only: %i[new create destroy]
    resources :users
    resources :versions
    resources :documents
    resources :projects  
    resources :groups
    resources :qr_code_positions
    resources :accesses
    resources :admin, only: %i[index]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/qr_code_position.rb
class QrCodePosition < ApplicationRecord
  has_many :documents
  belongs_to :user, counter_cache: true

  audited

  validates :name, :page, :x, :y, :size, presence: {notice: "aïe"}
end

app/controllers/qr_code_positions_controller.rb
class QrCodePositionsController < ApplicationController
  before_action :set_qr_code_position, only: [:show, :edit, :update, :destroy]
  before_action :check_logged_in

  # GET /qr_code_positions
  # GET /qr_code_positions.json
  def index
    if current_user.super_admin?
      @qr_code_positions = QrCodePosition.all
    else
      @qr_code_positions = QrCodePosition.where(user_id: current_user.id).order(:name)
    end
  end

  # GET /qr_code_positions/1
  # GET /qr_code_positions/1.json
  def show
  end

  # GET /qr_code_positions/new
  def new
    @qr_code_position = QrCodePosition.new
    session[:return_to] ||= request.referer
  end

  # GET /qr_code_positions/1/edit
  def edit
    session[:return_to] ||= request.referer
  end

  # POST /qr_code_positions
  # POST /qr_code_positions.json
  def create
    @qr_code_position = QrCodePosition.new(qr_code_position_params)
    @qr_code_position.user = current_user

    respond_to do |format|
      if @qr_code_position.save
        format.html { redirect_to session.delete(:return_to), notice: t('qrcode.create.confirmation') }
        format.json { render :show, status: :created, location: @qr_code_position }
      else
        format.html { render :new }
        format.json { render json: @qr_code_position.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /qr_code_positions/1
  # PATCH/PUT /qr_code_positions/1.json
  def update
    respond_to do |format|
      if @qr_code_position.update(qr_code_position_params)
        format.html { redirect_to session.delete(:return_to), notice: t('qrcode.update.confirmation') }
        format.json { render :show, status: :ok, location: @qr_code_position }
      else
        format.html { render :edit }
        format.json { render json: @qr_code_position.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /qr_code_positions/1
  # DELETE /qr_code_positions/1.json
  def destroy
    @qr_code_position.destroy
    respond_to do |format|
      format.html { redirect_to qr_code_positions_url, notice: t('qrcode.destroy.confirmation') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_qr_code_position
      @qr_code_position = QrCodePosition.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def qr_code_position_params
      params.require(:qr_code_position).permit(:page, :x, :y, :size, :name)
    end
end

app/helpers/qr_code_positions_helper.rb
module QrCodePositionsHelper
end

app/views/qr_code_positions/_form.html.erb
<%= form_with(model: qr_code_position, local: true) do |f| %>
  <% if qr_code_position.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(qr_code_position.errors.count, "error") %> prohibited this qr_code_position from being saved:</h2>

      <ul>
      <% qr_code_position.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-2">
      <%= t('qrcode.form.page') %> *
    </div>
    <div class="col-md-2">
      <%= f.number_field :page, class: "input-shorter", tabindex: 1 %>
    </div>
    <div class="col-md-8 grey">
      <%= t('qrcode.form.page_info') %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-2 mm">
      <%= t('qrcode.form.x') %> [mm] *
    </div>
    <div class="col-md-2">
      <%= f.number_field :x, class: "input-shorter", tabindex: 2 %>
    </div>
    
  </div>

  <div class="row">
    <div class="col-md-2 mm">
      <%= t('qrcode.form.y') %> [mm] *
    </div>
    <div class="col-md-2">
      <%= f.number_field :y, class: "input-shorter", tabindex: 3 %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-2 mm">
      <%= t('qrcode.form.size') %> [mm] *
    </div>
    <div class="col-md-2">
      <%= f.number_field :size, class: "input-shorter", tabindex: 4 %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-2">
      <%= t('qrcode.form.name') %> *
    </div>
    <div class="col-md-4">
      <%= f.text_field :name, tabindex: 5 %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-4 col-md-offset-2">
      <%= f.submit t('qrcode.submit'), tabindex: 6 %>
      <%= link_to t('qrcode.cancel'), :back, class: "btn" %>
    <div>
  </div>

  <div class="image-layout">
    <%= image_tag "qr_code_position.svg" %>
  </div>
<% end %>

app/views/qr_code_positions/edit.html.erb
<h1>Editing Qr Code Position</h1>

<%= render 'form', qr_code_position: @qr_code_position %>

<%= link_to 'Show', @qr_code_position %> |
<%= link_to 'Back', qr_code_positions_path %>

app/views/qr_code_positions/index.html.erb
<h1>Qr Code Positions</h1>

<%= link_to 'New Qr Code Position', new_qr_code_position_path, class: "btn" %>
<%= link_to 'Back to documents', documents_path, class: "btn" %>

<table class="table">
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th class="text-center"><%= t('qrcode.index.page') %></th>
      <th class="text-center"><%= t('qrcode.index.x') %></th>
      <th class="text-center"><%= t('qrcode.index.y') %></th>
      <th class="text-center"><%= t('qrcode.index.size') %></th>
    </tr>
  </thead>

  <tbody>
    <% @qr_code_positions.each do |qr_code_position| %>
      <tr>
        <td>
          <div class="dropdown">
            <a href="#" class="dropdown-toggle" type="button" data-toggle="dropdown">
            <span class="glyphicon glyphicon-chevron-down"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Edit', edit_qr_code_position_path(qr_code_position) %></li>
              <li><%= link_to 'Destroy', qr_code_position, method: :delete, data: { confirm: 'Are you sure?' }, class: "danger" %></li>
            </ul>
          </div>
        </td>
        <td><%= qr_code_position.name %></td>
        <td class="text-center"><%= qr_code_position.page %></td>
        <td class="text-center"><%= qr_code_position.x %> mm</td>
        <td class="text-center"><%= qr_code_position.y %> mm</td>
        <td class="text-center"><%= qr_code_position.size %> mm</td>
        <td>
        <% if qr_code_position.documents_count <= 0 %>
          <%= t('qrcode.index.not_used') %>
        <% else %>
          <%= pluralize(qr_code_position.documents_count, t('qrcode.index.document_used'), t('qrcode.index.documents_used')) %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/qr_code_positions/new.html.erb
<h1><%= t('qrcode.new.title') %></h1>

<%= render 'form', qr_code_position: @qr_code_position %>

app/views/qr_code_positions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Page:</strong>
  <%= @qr_code_position.page %>
</p>

<p>
  <strong>X:</strong>
  <%= @qr_code_position.x %>
</p>

<p>
  <strong>Y:</strong>
  <%= @qr_code_position.y %>
</p>

<p>
  <strong>Size:</strong>
  <%= @qr_code_position.size %>
</p>

<p>
  <strong>Name:</strong>
  <%= @qr_code_position.name %>
</p>

<%= link_to 'Edit', edit_qr_code_position_path(@qr_code_position) %> |
<%= link_to 'Back', qr_code_positions_path %>