config/routes.rb
Rails.application.routes.draw do

  get 'users/stats/:id',                to: 'users#stats'

  get 'projects/move_to_document/:id',  to: 'projects#move_to_document'
  get 'projects/move_to_access/:id',    to: 'projects#move_to_access'
  get 'projects/move_to_detail/:id',    to: 'projects#move_to_detail'
  get 'projects/all_download/:id',      to: 'projects#all_download'

  get 'documents/move_to_version/:id',  to: 'documents#move_to_version'

  post 'versions/download_pdf/',        to: 'versions#download_pdf'
  post 'versions/download_dxf/',        to: 'versions#download_dxf'
  get 'versions/make_current/:id',      to: 'versions#make_current'
  get 'checker/:encrypted_id',          to: 'versions#checker'
  
  get 'admin/projects',                 to: 'admin#projects'
  get 'admin/users',                    to: 'admin#users'
  get 'admin/new_user',                 to: 'admin#new_user'
  get 'admin/edit_user/:id',            to: 'admin#edit_user'
  get 'admin/logs',                     to: 'admin#logs'

  scope "(:locale)", locale: /en|fr|de/ do
    root 'static_pages#home'
    resource :session, only: %i[new create destroy]
    resources :users
    resources :versions
    resources :documents
    resources :projects  
    resources :groups
    resources :qr_code_positions
    resources :accesses
    resources :admin, only: %i[index]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/access.rb
class Access < ApplicationRecord
  attr_accessor :email

  audited
  
  belongs_to :user,    counter_cache: true
  belongs_to :project, counter_cache: true
end

app/models/admin.rb
class Admin

  def projects
    return Project.count
  end

  def projects_quantity(data)
    projects = Audits.where(auditable_type: "Project").group("DATE_TRUNC('day', created_at)", :action).count
    projects.sort_by { |date, value| date }
    p projects
    
    value = Project.where("created_at <= ?", 1.month.ago).count
    values = Hash.new
    projects.each do |project|
      if project[0][1] = "create"
        values[project[0][0]] = value + project[1]
      elsif project[0][1] == "destroy"
        values[project[0][0]] = value - project[1] 
      end
    end
    p "values"
    p values
    return values
  end

  def documents
    return Document.count
  end

  def documents_quantity(data)
    documents = Audits.where(auditable_type: "Document").group("DATE_TRUNC('day', created_at)", :action).count
    documents.sort_by { |date, value| date }
    p documents
    
    value = Document.where("created_at <= ?", 1.month.ago).count
    values = Hash.new
    documents.each do |document|
      if document[0][1] = "create"
        values[document[0][0]] = value + document[1]
      elsif document[0][1] == "destroy"
        values[document[0][0]] = value - document[1] 
      end
    end
    p "values"
    p values
    return values
  end

  def versions
    return Version.count
  end

  def versions_quantity(data)
    versions = Audits.where(auditable_type: "Version").group("DATE_TRUNC('day', created_at)", :action).count
    versions.sort_by { |date, value| date }
    p versions
    
    value = Version.where("created_at <= ?", 1.month.ago).count
    values = Hash.new
    versions.each do |version|
      if version[0][1] = "create"
        values[version[0][0]] = value + version[1]
      elsif version[0][1] == "destroy"
        values[version[0][0]] = value - version[1] 
      end
    end
    p "values"
    p values
    return values
  end

  def users
    return User.count
  end

  def users_quantity(data)
    users = Audits.where(auditable_type: "User").group("DATE_TRUNC('day', created_at)", :action).count
    users.sort_by { |date, value| date }
    p users
    
    value = User.where("created_at <= ?", 1.month.ago).count
    values = Hash.new
    users.each do |user|
      if user[0][1] = "create"
        values[user[0][0]] = value + user[1]
      elsif user[0][1] == "destroy"
        values[user[0][0]] = value - user[1] 
      end
    end
    p "values"
    p values
    return values
  end

  def span_end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/audits.rb
class Audits < ActiveRecord::Base
  belongs_to :user
end

app/models/document.rb
class Document < ApplicationRecord
  attr_accessor :position

  audited

  belongs_to :user,             counter_cache: true
  belongs_to :project,          counter_cache: true
  #belongs_to :group,            counter_cache: true
  belongs_to :qr_code_position, counter_cache: true

  has_many :versions, dependent: :destroy

  validates :title, :identifier, :position, presence: {notice: "aïe"}, on: :create

end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user,    counter_cache: true
  belongs_to :project, counter_cache: true

  #has_many :documents, dependent: :destroy
end

app/models/project.rb
class Project < ApplicationRecord

  audited

  belongs_to :user, counter_cache: true
  
  has_many :groups,    dependent: :destroy
  has_many :documents, dependent: :destroy
  has_many :versions,  dependent: :destroy
  has_many :accesses,  dependent: :destroy
  has_one :layout
  
  validates :name, :identifier, presence: {notice: "aïe"}
end

app/models/qr_code_position.rb
class QrCodePosition < ApplicationRecord
  has_many :documents
  belongs_to :user, counter_cache: true

  audited

  validates :name, :page, :x, :y, :size, presence: {notice: "aïe"}
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates_uniqueness_of :email, :case_sensitive => false
  validates :password, confirmation: true, on: :create
  validates :terms_of_service, acceptance: true, on: :create
  validates_length_of :password, in: 5..30, on: :create
  validates :check_password, confirmation: true, on: :update
  validates :first_name, :last_name, presence: {notice: "aïe"}

  has_many :projects,  dependent: :destroy
  has_many :groups,    dependent: :destroy
  has_many :documents, dependent: :destroy
  has_many :versions,  dependent: :destroy
  has_many :accesses,  dependent: :destroy
  has_many :qr_code_positions
  has_many :audits

  def check_password
    return unless password.present? || password_confirmation.present?
    # does not check the password length
  end
end

app/models/version.rb
class Version < ApplicationRecord

  audited

  belongs_to :user,     counter_cache: true
  belongs_to :project,  counter_cache: true
  belongs_to :document, counter_cache: true
  
  validates_uniqueness_of :version_number, :scope => [:project_id, :document_id]
  validates :version_number, :pdf_file, presence: {notice: "aïe"}

  mount_uploader :pdf_file, FileUploader
  mount_uploader :dxf_file, FileUploader
  mount_uploader :qrcode, QrcodeUploader
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :get_data

  def index
    @admin = Admin.new
    authorize @admin
    @projects_quantity  = @admin.projects_quantity(@data)
    @documents_quantity = @admin.documents_quantity(@data)
    @versions_quantity  = @admin.versions_quantity(@data)
    @users_quantity     = @admin.users_quantity(@data)

  end

  def projects
    @projects = Project.all
    #authorize @projects
  end

  def users
    @users = User.all.order(:last_name, :first_name)
  end

  def new_user
    @user = User.new
  end

  def edit_user
    @user = User.find(params[:id])
  end

  def logs
    @logs = Audits.all.order(:created_at).reverse
  end

  private

  def get_data
    @data = Audits.where("created_at > ?", 1.month.ago).as_json
  end

end

app/helpers/accesses_helper.rb
module AccessesHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/versions_helper.rb
module VersionsHelper

end

app/views/admin/_user_form.html.erb
<%= form_with(model: user, local: true) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-2">ID</div>
    <div class="col-md-4"><%= user.id %></div>
  </div>

  <div class="row">
    <div class="col-md-2">Created at</div>
    <div class="col-md-4"><%= user.created_at %></div>
  </div>

  <div class="row">
    <div class="col-md-2">Last updated at</div>
    <div class="col-md-4"><%= user.updated_at %></div>
  </div>

  <div class="row">
    <div class="col-md-2">First name</div>
    <div class="col-md-4">
      <%= f.text_field :first_name, tabindex: 1 %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-2">Last name</div>
    <div class="col-md-4">
      <%= f.text_field :last_name, tabindex: 2 %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-2">Email</div>
    <div class="col-md-4">
      <%= f.text_field :email, tabindex: 3 %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-2">Password</div>
    <div class="col-md-4">
      <%= f.text_field :password, tabindex: 4 %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-2">Phone</div>
    <div class="col-md-4">
      <%= f.text_field :phone, tabindex: 6 %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-2">Company</div>
    <div class="col-md-4">
      <%= f.text_field :company, tabindex: 7 %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-2">Discipline</div>
    <div class="col-md-4">
      <%= f.text_field :discipline, tabindex: 8 %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-2">Super admin?</div>
    <div class="col-md-4">
      <%= f.check_box :super_admin %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-4 col-md-offset-2">
      <%= f.submit t('user.submit'), tabindex: 9 %>
      <%= link_to t('user.cancel'), :back, class: "btn" %>
    </div>
  </div>
<% end %>

app/views/admin/edit_user.html.erb
<%= render 'user_form', user: @user %>

app/views/admin/index.html.erb
<h1><%= t('admin.index.title') %></h1>


<div class="row">
  <div class="col-md-2 col-xl-2">
    Projects: <%= @admin.projects %><br>
    Documents: <%= @admin.documents %><br>
    Versions: <%= @admin.versions %><br>
    Users: <%= @admin.users %>
  </div>
  <div class="col-md-3 col-xl-3">
    <%= pie_chart({
      "Active" => User.where(active: true).count,
      "Inactive" => User.where(active: false).count
      }, colors: ["#ddd", "#777"],
      legend: "bottom",
      width: "200px")
     %>
  </div>
  <div class="col-md-3 col-xl-3">
    <span class="grey">New users</span><br><br>
    <%= column_chart User.group_by_day(:created_at).count, height: "220px", width: "95%", curve: false, ytitle: "Users", colors: ["#ddd", "#777"] %> 
  </div>
  <div class="col-md-3 col-xl-3">
    <span class="grey">Users</span><br><br>
    <%= line_chart @users_quantity, height: "220px", width: "95%", curve: false, points: false, colors: ["#ddd", "#777"] %>
  </div>
</div>

<div class="row">
  <br><br><br>
</div>


<div class="row">
  <div class="col-md-3 col-xl-3 col-md-offset-2">
    <span class="grey">New projects</span><br><br>
    <%= column_chart Project.group_by_day(:created_at).count, height: "220px", width: "95%", curve: false, colors: ["#ddd", "#777"] %>
    <br><br><br>
    <span class="grey">Projects</span><br><br>
    <%= line_chart @projects_quantity, height: "220px", width: "95%", curve: false, points: false, colors: ["#ddd", "#777"] %>
  </div>

  <div class="col-md-3 col-xl-3">
    <span class="grey">New documents</span><br><br>
    <%= column_chart Document.group_by_day(:created_at).count, height: "220px", width: "95%", curve: false, ytitle: "Documents", colors: ["#ddd", "#777"] %>
    <br><br><br>
    <span class="grey">Documents</span><br><br>
    <%= line_chart @documents_quantity, height: "220px", width: "95%", curve: false, points: false, colors: ["#ddd", "#777"] %>
  </div>

  <div class="col-md-3 col-xl-3">
    <span class="grey">New versions</span><br><br>
    <%= column_chart Version.group_by_day(:created_at).count, height: "220px", width: "95%", curve: false, ytitle: "Versions", colors: ["#ddd", "#777"] %>
    <br><br><br>
    <span class="grey">Versions</span><br><br>
    <%= line_chart @versions_quantity, height: "220px", width: "95%", curve: false, points: false, colors: ["#ddd", "#777"] %>
  </div>
</div>

app/views/admin/logs.html.erb
<h1>Logs</h1>

<table class="table">
  <thead>
    <tr>
      <th>ID</th>
      <th>Time</th> 
      <th>Type</th>
      <th>Action</th>
      <th>User</th>
      <th>Values</th>
      <th>IP</th>  
    </tr>
  </thead>

  <tbody>
  <% @logs.each do |log| %>
    <tr>
      <td><%= log.id %></td>
      <td><%= log.created_at %></td>
      <td><%= log.auditable_type %></td>
      <td><%= log.action %></td>
      <td>
          <% if log.user %>
          <%= log.user.email %>
          <% end %>
      </td>
      <td><%= link_to "Detail", versions_path, class: "btn super-sharp" %></td>
      <td><%= log.remote_address %></td>
    </tr>
  <% end %>
  </tbody>

</table>

app/views/admin/new_user.html.erb
<%= render 'user_form', user: @user %>

app/views/admin/projects.html.erb
<h1>Projects</h1>

<table class="table">
  <% @projects.each do |project| %>
    <tr>
      <td><%= link_to project.id, project_path(project.id) %></td>
      <td><%= "#{project.identifier} - #{project.name}" %></td>
      <td><%= "Documents : #{project.documents_count}" %><br>
          <%= "Versions : #{project.versions_count}" %></td>
      <td>Owner: <%= project.user.email %></td>
      <td><%= "Accesses : #{project.accesses_count}" %></td>
      <td><%= "Created at : #{project.created_at.strftime("%d.%m.%Y %T")}" %><br>
          <%= "Last update at : #{project.updated_at.strftime("%d.%m.%Y %T")}" %></td>
    </tr>
  <% end %>
</table>

app/views/admin/users.html.erb
<h1>Users</h1>

<table class="table">
  <thead>
    <tr>
      <th colspan="2"></th>
      <th>ID</th>
      <th>Last name</th>
      <th>First name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Company</th>
      <th>Discipline</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td>
          <% if user.super_admin? %>
            <span class="glyphicon glyphicon-star"></span>
          <% end %>
        </td>
        <td>
          <% if !user.active? %>
            <span class="glyphicon glyphicon-remove"></span>
          <% end %>
        </td>
        <td><%= user.id %></td>
        <td><%= user.last_name %></td>
        <td><%= user.first_name %></td>
        <td><%= user.email %></td>
        <td><%= user.phone %></td>
        <td><%= user.company %></td>
        <td><%= user.discipline %></td>
        <td><%= link_to 'Edit', controller: :admin, action: :edit_user, id: user.id, class: "btn super-sharp" %>
            <%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn super-sharp danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/_admin_tools.html.erb
<div class="admin-tools">
  <h3>Admin tools</h3>

  <ul>
    
    <li><%= link_to "Admin board", admin_index_path %></li>
    <li class="h-line"></li>
    <li><%= link_to "Users", controller: :admin, action: :users %></li>
    <li><%= link_to "New user", controller: :admin, action: :new_user %></li>
    <li class="h-line"></li>
    <li><%= link_to "Projects", controller: :admin, action: :projects %></li>
    <li><%= link_to "New project", new_project_path %></li>
    <li class="h-line"></li>
    <li><%= link_to "Logs", controller: :admin, action: :logs %></li>
    
  </ul>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse">
<div class="container">
  <%= link_to "version checker", projects_path, class: "navbar-brand" %>

  <ul class="nav navbar-nav navbar-right">
    <% if @projects.any? %>
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <%= current_project ? "#{current_project.identifier} : #{current_project.name}" : t('navbar.projects') %> <span class="caret"></span>
      </a>
      <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
        
          <% @projects.each do |project| %>
            <li><%= link_to "#{project.identifier} : #{project.name}",  controller: :projects, action: :move_to_document, id: project.id %></li>
          <% end %>
          <li class="divider"></li>
          <li><%= link_to t('navbar.my_projects'), projects_path %></li>
          <li><%= link_to t('navbar.new_project'), new_project_path %></li> 
      </ul>
    </li>
    <% end %>

    <li class="nav-menu-separator"></li>
    <li><%= link_to "EN", url_for(locale: 'en') %></li>
    <li><%= link_to "FR", url_for(locale: 'fr') %></li>

    <li class="nav-menu-separator"></li>
        <% if logged_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= "#{current_user.first_name} #{current_user.last_name}" %>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <li><%= link_to t('navbar.my_account'), edit_user_path(current_user.id) %></li>
              <li><%= link_to t('navbar.my_stats'), controller: :users, action: :stats, id: current_user.id %></li> 
              <li><%= link_to t('navbar.logout'), session_path, method: :delete %></li>
            </ul>
          </li>
          <li class="nav-menu-separator"></li>
        <% else %>
          <li>
            <%= link_to t('navbar.signup'), new_user_path %>
          </li>
          <li class="nav-menu-separator"></li>
          <li class="">
            <%= link_to t('navbar.login'), new_session_path %>
          </li>
        <% end %>
        <li class="nav-menu-separator"></li>
  </ul>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VersionChecker</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
     
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container">
    <%= render 'layouts/header' %>
    
    <% if current_user != nil && current_user.super_admin? %>
      <div class="admin-content">
        <div class="admin-board">
          <%= yield %>
        </div>
        <div class="admin-pannel">
          <%= render 'layouts/admin_tools' %>
        </div>
      </div>
    <% else %>
      <div class="main-content">
        <%= yield %>
      </div>
    <% end %>
    
    <%= render 'layouts/footer' %>
  </body>
</html>