config/routes.rb
Rails.application.routes.draw do

  get 'users/stats/:id',                to: 'users#stats'

  get 'projects/move_to_document/:id',  to: 'projects#move_to_document'
  get 'projects/move_to_access/:id',    to: 'projects#move_to_access'
  get 'projects/move_to_detail/:id',    to: 'projects#move_to_detail'
  get 'projects/all_download/:id',      to: 'projects#all_download'

  get 'documents/move_to_version/:id',  to: 'documents#move_to_version'

  post 'versions/download_pdf/',        to: 'versions#download_pdf'
  post 'versions/download_dxf/',        to: 'versions#download_dxf'
  get 'versions/make_current/:id',      to: 'versions#make_current'
  get 'checker/:encrypted_id',          to: 'versions#checker'
  
  get 'admin/projects',                 to: 'admin#projects'
  get 'admin/users',                    to: 'admin#users'
  get 'admin/new_user',                 to: 'admin#new_user'
  get 'admin/edit_user/:id',            to: 'admin#edit_user'
  get 'admin/logs',                     to: 'admin#logs'

  scope "(:locale)", locale: /en|fr|de/ do
    root 'static_pages#home'
    resource :session, only: %i[new create destroy]
    resources :users
    resources :versions
    resources :documents
    resources :projects  
    resources :groups
    resources :qr_code_positions
    resources :accesses
    resources :admin, only: %i[index]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/accesses_controller.rb
class AccessesController < ApplicationController
  before_action :set_access, only: [:show, :edit, :update, :destroy]
  before_action :set_roles, only: [:new, :create, :edit]
  before_action :check_logged_in

  # GET /accesses
  # GET /accesses.json
  def index
    if current_user.super_admin
      @accesses = Access.all
    else
      @accesses = Access.where(project_id: session[:current_project_id]).order(:role).reverse_order
    end
  end

  # GET /accesses/1
  # GET /accesses/1.json
  def show
  end

  # GET /accesses/new
  def new
    @access = Access.new
  end

  # GET /accesses/1/edit
  def edit
  end

  # POST /accesses
  # POST /accesses.json
  def create
    @access = Access.new(access_params)
    authorize @access
    @access.project = current_project
    p current_project
    
    if user = User.find_by(email: @access.email)
      p "user exists"
      @access.user = user
      p @access
      respond_to do |format|
        if @access.save
          p "access created"
          format.html { redirect_to accesses_path, notice: t('access.create.confirmation') }
          format.json { render :show, status: :created, location: @access }
        else
          format.html { render :new }
          format.json { render json: @access.errors, status: :unprocessable_entity }
        end
      end
    else
      respond_to do |format|
      # TODO
      # send invitiation email
        format.html { redirect_to projects_path, notice: "#{t('access.create.send_email_confirmation')} : #{@access.email}" }
      end
    end
  end

  # PATCH/PUT /accesses/1
  # PATCH/PUT /accesses/1.json
  def update
    authorize @access
    respond_to do |format|
      if @access.update(access_params)
        format.html { redirect_to accesses_path, notice: t('access.update.confirmation') }
        format.json { render :show, status: :ok, location: @access }
      else
        format.html { render :edit }
        format.json { render json: @access.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accesses/1
  # DELETE /accesses/1.json
  def destroy
    authorize @access
    @access.destroy
    respond_to do |format|
      format.html { redirect_to accesses_url, notice: t('access.destroy.confirmation') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_access
      @access = Access.find(params[:id])
    end

    def set_roles
      @roles = [
        [t('access.role.basicUser'), 'basicUser'],
        [t('access.role.projectAdmin'), 'projectAdmin']
      ]
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def access_params
      params.require(:access).permit(:role, :user_id, :project_id, :email)
    end
end

app/helpers/accesses_helper.rb
module AccessesHelper
end

app/views/accesses/_form.html.erb
<%= form_with(model: access, local: true) do |f| %>
  <% if access.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(access.errors.count, "error") %> prohibited this access from being saved:</h2>

      <ul>
      <% access.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-2">
      <%= t('access.new.user') %> *
    </div>
    <div class="col-md-4">
      <%= @access.user.email %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-2">
      <%= t('access.new.role') %> *
    </div>
    <div class="col-md-4">
      <%= f.select(:role, options_for_select(@roles, @access.role)) %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-4 col-md-offset-2">
      <%= f.submit t('access.submit'), class: "btn", tabindex: 3 %>
      <%= link_to t('access.cancel'), accesses_path, class: "btn" %>
    </div>
  </div>

<% end %>

app/views/accesses/edit.html.erb
<h1><%= t('access.edit.title') %></h1>

<%= form_with(model: @access, local: true) do |f| %>
  <% if @access.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@access.errors.count, "error") %> prohibited this access from being saved:</h2>

      <ul>
      <% @access.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-2">
      <%= t('access.new.user') %> *
    </div>
    <div class="col-md-4">
      <%= @access.user.email %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-2">
      <%= t('access.new.role') %> *
    </div>
    <div class="col-md-4">
      <%= f.select(:role, options_for_select(@roles, @access.role)) %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-4 col-md-offset-2">
      <%= f.submit t('access.submit'), class: "btn", tabindex: 3 %>
      <%= link_to t('access.cancel'), accesses_path, class: "btn" %>
    </div>
  </div>

<% end %>

  

app/views/accesses/index.html.erb
<h1><%= t('access.index.title') %></h1>

<div class="row">
  <div class="col-md-12">
    <%= link_to t('access.back'), :back, class: "btn" %>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <% if policy(@accesses).create? %>
      <%= link_to t('access.index.new'), new_access_path, class: "btn" %>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <table class="table">
      <% @accesses.each do |access| %>
      <tr>
        <td class="middle">
          <div class="dropdown">
            <a href="#" class="dropdown-toggle" type="button" data-toggle="dropdown">
            <span class="glyphicon glyphicon-chevron-down"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to t('access.index.detail'), user_path(access.user) %></li>
              <% if policy(access).update? %>
                <li><%= link_to t('access.index.edit'), edit_access_path(access) %></li>
              <% end %>
              <% if policy(access).destroy? %>
                <li><%= link_to t('access.index.delete'), access, method: :delete, data: { confirm: 'Are you sure?' }, class: "danger" %></li>
              <% end %>
            </ul>
          </div>
        </td>
        <td class="middle"><%= "#{access.user.first_name} #{access.user.last_name}" %></td>
        <td class="middle"><%= access.user.company %></td>
        <td class="middle"><%= access.user.discipline %></td>
        <td class="middle"><%= access.user.email %></td>
        <td class="middle"><%= t('access.role.'+access.role) %></td>
      </tr>
      <% end %>

    </table>
  </div>
</div>

app/views/accesses/new.html.erb
<h1><%= t('access.new.title') %></h1>

<%= form_with(model: @access, local: true) do |f| %>
  <% if @access.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@access.errors.count, "error") %> prohibited this access from being saved:</h2>

      <ul>
      <% @access.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-2">
      <%= t('access.new.user') %> *
    </div>
    <div class="col-md-4">
      <%= f.text_field :email, tabindex: 1 %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-2">
      <%= t('access.new.role') %> *
    </div>
    <div class="col-md-4">
      <%= f.select(:role, options_for_select(@roles, @access.role)) %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-4 col-md-offset-2">
      <%= f.submit t('access.submit'), class: "btn", tabindex: 3 %>
      <%= link_to t('access.cancel'), accesses_path, class: "btn" %>
    </div>
  </div>

<% end %>

app/views/accesses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Role:</strong>
  <%= @access.role %>
</p>

<p>
  <strong>User:</strong>
  <%= @access.user_id %>
</p>

<p>
  <strong>Project:</strong>
  <%= @access.project_id %>
</p>

<%= link_to 'Edit', edit_access_path(@access) %> |
<%= link_to 'Back', accesses_path %>