config/routes.rb
Rails.application.routes.draw do

  get 'users/stats/:id',                to: 'users#stats'

  get 'projects/move_to_document/:id',  to: 'projects#move_to_document'
  get 'projects/move_to_access/:id',    to: 'projects#move_to_access'
  get 'projects/move_to_detail/:id',    to: 'projects#move_to_detail'
  get 'projects/all_download/:id',      to: 'projects#all_download'

  get 'documents/move_to_version/:id',  to: 'documents#move_to_version'

  post 'versions/download_pdf/',        to: 'versions#download_pdf'
  post 'versions/download_dxf/',        to: 'versions#download_dxf'
  get 'versions/make_current/:id',      to: 'versions#make_current'
  get 'checker/:encrypted_id',          to: 'versions#checker'
  
  get 'admin/projects',                 to: 'admin#projects'
  get 'admin/users',                    to: 'admin#users'
  get 'admin/new_user',                 to: 'admin#new_user'
  get 'admin/edit_user/:id',            to: 'admin#edit_user'
  get 'admin/logs',                     to: 'admin#logs'

  scope "(:locale)", locale: /en|fr|de/ do
    root 'static_pages#home'
    resource :session, only: %i[new create destroy]
    resources :users
    resources :versions
    resources :documents
    resources :projects  
    resources :groups
    resources :qr_code_positions
    resources :accesses
    resources :admin, only: %i[index]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/document.rb
class Document < ApplicationRecord
  attr_accessor :position

  audited

  belongs_to :user,             counter_cache: true
  belongs_to :project,          counter_cache: true
  #belongs_to :group,            counter_cache: true
  belongs_to :qr_code_position, counter_cache: true

  has_many :versions, dependent: :destroy

  validates :title, :identifier, :position, presence: {notice: "aïe"}, on: :create

end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :edit, :update, :destroy]
  before_action :check_logged_in
  
  # GET /documents
  # GET /documents.json
  def index
    @documents = Document.where(project_id: session[:current_project_id]).order(:identifier)
    @project = current_project
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
  end

  # GET /documents/new
  def new
    @document = Document.new
    @document.project = current_project
    authorize @document
    @qr_code_positions = QrCodePosition.where(user_id: current_user.id).pluck(:name, :id)
  end

  # GET /documents/1/edit
  def edit
    authorize @document
    @qr_code_positions = QrCodePosition.where(user_id: current_user.id).pluck(:name, :id)
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(document_params)
    @document.user = current_user
    @document.project = current_project
    @document.qr_code_position = QrCodePosition.find(@document.position)
    authorize @document
    respond_to do |format|
      if @document.save
        format.html { redirect_to documents_path, notice: t('document.create.confirmation') }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    authorize @document
    params = document_params
    params[:qr_code_position] = QrCodePosition.find(document_params[:position])
    
    respond_to do |format|
      if @document.update(params)
        format.html { redirect_to documents_path, notice: t('document.update.confirmation') }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    authorize @document
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url, notice: t('document.destroy.confirmation') }
      format.json { head :no_content }
    end
  end

  def move_to_version
    session[:current_document_id] = params[:id]
    if params[:new] == 'true'
      redirect_to new_version_path
    else
      redirect_to versions_path
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_params
      params.require(:document).permit(:identifier, :title, :sub_title, :doc_type, :size, :group, :last_version, :last_version_date, :position)
    end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_form.html.erb
<%= form_with(model: document, local: true) do |f| %>
  <% if document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% document.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if @qr_code_positions.any? %>

  <div class="row">
    <div class="col-md-2 middle-btn">
      <%= t('document.form.qrcode-layout') %> *
    </div>
    <div  class="col-md-4">
      <%= f.select :position, options_for_select(@qr_code_positions, @document.qr_code_position ? @document.qr_code_position.name : "") %>
    </div>
    <div class="col-md-6">
    <%= link_to t('document.form.manage_layouts'), qr_code_positions_path, class: "btn sharp" %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-2">
      <%= t('document.form.identifier') %> *
    </div>
    <div class="col-md-4">
      <%= f.text_field :identifier, tabindex: 1 %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-2">
      <%= t('document.form.name') %> *
    </div>
    <div class="col-md-4">
      <%= f.text_field :title, tabindex: 2 %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-2">
      <%= t('document.form.sub_title') %>
    </div>
    <div class="col-md-4">
      <%= f.text_field :sub_title, tabindex: 3 %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-2">
      <%= t('document.form.doc_type') %>
    </div>
    <div class="col-md-4">
      <%= f.text_field :doc_type, tabindex: 4 %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-2">
      <%= t('document.form.size') %>
    </div>
    <div class="col-md-4">
      <%= f.text_field :size, tabindex: 5 %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-4 col-md-offset-2">
      <%= f.submit t('document.submit'), class: "btn", tabindex: 7 %>
      <%= link_to t('document.back'), documents_path, class: "btn" %>
    </div>
  </div>

  <% else %>
  <div class="row">
    <div class="col-md-2 middle-btn">
      <%= t('document.form.qrcode-layout') %> *
    </div>
    <div  class="col-md-4">
      <%= link_to t('document.form.create_new_layout'), new_qr_code_position_path, class: "btn sharp" %>
    </div>
    <div class="col-md-6">
      <%= link_to t('document.form.manage_layouts'), qr_code_positions_path, class: "btn sharp" %>
    </div>
  </div>
  <% end %>
  
<% end %>

app/views/documents/edit.html.erb
<h1><%= t('document.edit.title') %></h1>

<%= render 'form', document: @document %>

app/views/documents/index.html.erb
<h1><%= "#{t('document.index.title')} : #{current_project.identifier} - #{current_project.name}" %></h1>

<%= link_to t('document.index.new_document'), new_document_path, class: "btn" %>
<%= link_to t('document.back'), projects_path, class: "btn"%>


<table class="table">
  <tbody>
    <% @documents.each do |document| %>
      <tr>
        <td class="middle">
          <div class="dropdown">
            <a href="#" class="dropdown-toggle" type="button" data-toggle="dropdown">
            <span class="glyphicon glyphicon-chevron-down"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to t('document.edit_button'), edit_document_path(document) %></li>
              <li>
                <% if policy(document).destroy? %>
                  <%= link_to t('document.delete'), document, method: :delete, data: { confirm: 'Are you sure?' }, class: "danger" %>
                <% end %>
              </li>
              <li><%= link_to t('document.index.add_version'),   {controller: :documents, action: :move_to_version, id: document.id, new: true} %></li> 
              <li><%= link_to t('document.index.show_versions'), {controller: :documents, action: :move_to_version, id: document.id, new: false} %></li>
            </ul>
          </div>
        </td>
        <td class="middle">
          <h4>
          <%= link_to controller: :documents, action: :move_to_version, id: document.id, new: false do %>
            <%= document.identifier %>
          <% end %>
          </h4>
        </td>
        <td class="middle">
          <strong><%= document.title %></strong><br>
          <%= document.sub_title %>
        </td>

        <td class="middle">
          <%= "#{document.doc_type}" %><br>
          <%= "#{document.size}" %>
        </td>

        <td class="middle">
          <%= document.qr_code_position.name %>
        </td>

        <td class="middle">
          <%= "#{t('document.index.current_version')} : #{document.last_version}" %><br>
          <small><%= "#{t('document.index.current_version_date')} : #{document.last_version_date}" %></small><br>
          <small><%= "#{t('document.index.versions')} : #{document.versions_count}" %></small>
        </td>

      </tr>
    <% end %>
  </tbody>
</table>

app/views/documents/new.html.erb
<h1><%= t('document.new.title') %></h1>

<%= render 'form', document: @document %>

app/views/documents/show.html.erb
<p>
  <strong>Identifier:</strong>
  <%= @document.identifier %>
</p>

<p>
  <strong>Title:</strong>
  <%= @document.title %>
</p>

<p>
  <strong>Sub title:</strong>
  <%= @document.sub_title %>
</p>

<p>
  <strong>Type:</strong>
  <%= @document.doc_type %>
</p>

<p>
  <strong>Size:</strong>
  <%= @document.size %>
</p>

<%= link_to 'Edit', edit_document_path(@document) %> |
<%= link_to 'Back', documents_path %>